### ISSUE TITLE
Game crash, "The call method_14175 is not cancellable"

### ISSUE THREAD

**Issue by MatiCugno69** [nvb-uy/YSNS#1]
im gonna be honest, i have currently 290 mods on Fabric, and the only information that I got from the crash report was this line at the beginning:

"at net.minecraft.class_3218.handler$oml001$ysns$addEntity(class_3218.java:29717)"

I will attach the full crash report, and also my personal configuration file. Thanks for developing this mod!

[crash-2024-08-03_20.09.22-server.txt](https://github.com/user-attachments/files/16483221/crash-2024-08-03_20.09.22-server.txt)

[disabled_entities.txt](https://github.com/user-attachments/files/16483220/disabled_entities.txt)

**Comment by nvb-uy** [comment]
Update the mod
