### ISSUE TITLE
Mod not loading on 1.8.9

### ISSUE THREAD

**Issue by Sayasam42** [nvb-uy/YSNS#2]
Hello,

I have added this mod into MultiMC with Forge for Minecraft 1.8.9, but despite trying several mod jars (for Forge), the mod always fails to load.

Link to log:
[https://paste.ee/p/aq3hn](url)

The fun part is that it tries to load classes from the Fabric folder, but even if I delete this folder in the mod jar, it fails to load classes from the Forge folder as well.

I see that Minecraft versions supported by the mod only go down to 1.17. Is there a reason why older versions are not supported ?

Thanks

**Comment by nvb-uy** [comment]
I don't know how you can expect a 1.20.1 mod for fabric to support a 9 year old version with a completely different mod loader.
Legacy support is not planned.
