### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by LarxKuba** [nvb-uy/YSNS#3]
I am using this mod on a server to lower the spawn rates of creepers and endermen and have completely turned of the spawn of phantoms however none of the changes are visible ingame. Firstly, I still see 4 creepers spawning in a 5x5 area on 0.1 spawn and see the usual amount of endermen although its spawn rate is set to 0.3 . Secondly, phantoms still spawn.

I am running version 2.0.1 of this mod on 1.20.1 Fabric

config:
"dimensions": [
    {
      "entityId": "minecraft:creeper",
      "dimension": "minecraft:overworld",
      "spawn_chance": 0.1,
      "entityId": "minecraft:enderman",
      "dimension": "minecraft:overworld",
      "spawn_chance": 0.3
    }
  ],

config 2:

"disabled": [
    "miecraft:phantom"
  ],

**Comment by nvb-uy** [comment]
That is not how the config works. Please make a new object instead of adding more data to the existing one, it should look like this:

```
    {
        "entityId": "minecraft:creeper",
        "dimension": "minecraft:overworld",
        "spawn_chance": 0.1
    },
    {
        "entityId": "minecraft:enderman",
        "dimension": "minecraft:overworld",
        "spawn_chance": 0.3
    }
```

As for the phantom, it doesn't spawn because you typed out "miecraft" instead of "minecraft".
