### ISSUE TITLE
Can't join world "Couldn't place player in world"

### ISSUE THREAD

**Issue by thelyric27** [nvb-uy/YSNS#7]
I'm working on a cobblemon modpack and wanted to disable spawns for most vanilla mobs. After adding them all to the config though the player is blocked from spawning somehow? And I definitely didn't put "minecraft:player" in the list of disabled entities or anything. What's going on here?

Minecraft version: 1.20.1
Mod loader: Quilt 0.26.4-beta.7
Mod version: 2.0.1

Log (modlist in log): https://mclo.gs/3dFSgdr
Config: https://mclo.gs/Nqb5DvC

**Comment by nvb-uy** [comment]
Remove the comma in the last entry, commas should only be added if there's another entry next

**Comment by thelyric27** [comment]
Thank you, that worked lol. Classic syntax error moment.
